query getAllUsers {
    getAllUsers {
        id
        username
        email
        firstname
        lastname
        role
        birthdate
        phone
        isVerified
        createdAt
        updatedAt
    }
}