query getUserById($id: Float!) {
    getUserById(id: $id) {
        id
        username
        email
        firstname
        lastname
        role
        birthdate
        phone
        isVerified
        createdAt
        updatedAt
    }
}